# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170707_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(max_length=30),
        ),
    ]
