# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='comment_text',
        ),
    ]
