# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_likemodel_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
