# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(max_length=250),
        ),
    ]
